/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author poolm
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    Conexion cc = new Conexion();
    Connection con=cc.conexion();
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBRegistro = new javax.swing.JButton();
        jLIcono = new javax.swing.JLabel();
        jBTSalir = new javax.swing.JButton();
        jTFUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFContraseña = new javax.swing.JTextField();
        JBInicia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBRegistro.setText("Registrarse");
        jBRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jBRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Usuaeio.png"))); // NOI18N
        getContentPane().add(jLIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 210));

        jBTSalir.setBackground(new java.awt.Color(240, 60, 25));
        jBTSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBTSalir.setText("X");
        jBTSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBTSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));
        getContentPane().add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 130, -1));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, -1));
        getContentPane().add(jTFContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, -1));

        JBInicia.setText("Iniciar");
        JBInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBIniciaActionPerformed(evt);
            }
        });
        getContentPane().add(JBInicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLFondo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/pngtree-gradient-blue-light-emitting-h5-background-material-photo-682876.jpg"))); // NOI18N
        jLFondo.setText("Bienvenido");
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistroActionPerformed
        RegistroUsuarios llama = new RegistroUsuarios();
        llama.setVisible(true);
    }//GEN-LAST:event_jBRegistroActionPerformed
public boolean validar(){
    boolean val=false;
    
        try {
            String u=jTFUsuario.getText(),c=jTFContraseña.getText();
            String SQL="Select * From registrousuarios Where Usuario='"+u+"' and contrasena='"+c+"';";
            Statement at = con.createStatement();
            ResultSet rs=at.executeQuery(SQL);
            if (rs.next()) {
                val=true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    return val;
}
    private void JBIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBIniciaActionPerformed
        if (jTFUsuario.getText().isEmpty() || jTFContraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debes llenar todos los campos");
        }else{
            if (validar()) {
                Bienvenida i = new Bienvenida();
                i.setVisible(true);
                this.dispose();
            } else {
                 JOptionPane.showMessageDialog(null,"Debes llenar todos los campos");
            }
        }
    }//GEN-LAST:event_JBIniciaActionPerformed

    private void jBTSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBTSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBInicia;
    private javax.swing.JButton jBRegistro;
    private javax.swing.JButton jBTSalir;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLIcono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFContraseña;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
