/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author poolm
 */
public class RegistroPc extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPc
     */
    Computadora compu;
    Conexion conexion;
    public RegistroPc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFPlaca = new javax.swing.JTextField();
        jTFProcesador = new javax.swing.JTextField();
        jTFTarjeta = new javax.swing.JTextField();
        jTFDisco = new javax.swing.JTextField();
        jTFFuente = new javax.swing.JTextField();
        jTFGabinete = new javax.swing.JTextField();
        jBComprar = new javax.swing.JButton();
        IconoPC = new javax.swing.JLabel();
        jCBRam = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa Base:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Procesador:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ram:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarjeta de Video:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Disco Duro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fuente de Poder:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gabinete:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(jTFPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, -1));
        getContentPane().add(jTFProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, -1));
        getContentPane().add(jTFTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, -1));
        getContentPane().add(jTFDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, -1));
        getContentPane().add(jTFFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));
        getContentPane().add(jTFGabinete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, -1));

        jBComprar.setText("Comprar");
        jBComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jBComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 329, -1, -1));

        IconoPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/indice.png"))); // NOI18N
        IconoPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoPCMouseClicked(evt);
            }
        });
        getContentPane().add(IconoPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jCBRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 GB", "4 GB", "8 GB", "12 GB", "16 GB", "32 GB", "64 GB" }));
        getContentPane().add(jCBRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondo-azul-degradado-oscuro_1258-1365.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carrito");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void cargarDatos(){
        if (jTFPlaca.getText().isEmpty() || jTFProcesador.getText().isEmpty() || jTFTarjeta.getText().isEmpty() || jTFDisco.getText().isEmpty() || jTFFuente.getText().isEmpty() || jTFGabinete.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debes llenar todos los campos");
        }else{
            compu = new Computadora();
            compu.setPlacaBase(jTFPlaca.getText());
            compu.setProcesador(jTFProcesador.getText());
            compu.setRam(Integer.parseInt(jCBRam.getSelectedItem().toString()));
            compu.setTarjetaVideo(jTFTarjeta.getText());
            compu.setDiscoDuro(jTFDisco.getText());
            compu.setFuente(jTFFuente.getText());
            compu.setGabinete(jTFGabinete.getText());
        }
    }

    private void jBComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComprarActionPerformed
        try {
            cargarDatos();
            conexion = new Conexion();
            System.out.println("Objeto: "+compu.toString());
            if (conexion.registrarComputadora(compu)>0) {
                JOptionPane.showMessageDialog(null,"Registro Exitoso");
            }else{
                JOptionPane.showMessageDialog(null,"Error al registrar");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBComprarActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Carrito i = new Carrito();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       Bienvenida i = new Bienvenida();
       i.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void IconoPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoPCMouseClicked
       try {
            cargarDatos();
            conexion = new Conexion();
            System.out.println("Objeto: "+compu.toString());
            if (conexion.registrarComputadora(compu)>0) {
                JOptionPane.showMessageDialog(null,"Registro Exitoso");
            }else{
                JOptionPane.showMessageDialog(null,"Error al registrar");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IconoPCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoPC;
    private javax.swing.JButton jBComprar;
    private javax.swing.JComboBox<String> jCBRam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTFDisco;
    private javax.swing.JTextField jTFFuente;
    private javax.swing.JTextField jTFGabinete;
    private javax.swing.JTextField jTFPlaca;
    private javax.swing.JTextField jTFProcesador;
    private javax.swing.JTextField jTFTarjeta;
    // End of variables declaration//GEN-END:variables
}
