/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author poolm
 */
public class Update extends javax.swing.JFrame {

    public String id;
    public Update() {
        initComponents();
        mostrartabla();
        this.setLocationRelativeTo(null);
        TablaCar.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (TablaCar.getSelectedRow() != -1 )
                {
                    int fila = TablaCar.getSelectedRow();
                    id = TablaCar.getValueAt(fila, 0).toString();
                    jTFPlacaBase.setText(TablaCar.getValueAt(fila, 1).toString());
                    jTFProcesador.setText(TablaCar.getValueAt(fila, 2).toString());
                    jTFRam.setText(TablaCar.getValueAt(fila, 3).toString());
                    jTFTarjetaV.setText(TablaCar.getValueAt(fila, 4).toString());
                    jTFDd.setText(TablaCar.getValueAt(fila, 5).toString());
                    jTFFuente.setText(TablaCar.getValueAt(fila, 6).toString());
                    jTFGabinete.setText(TablaCar.getValueAt(fila, 7).toString());
                    
                }
            }
        });
        
        
    }
    ControladorBusqueda cbusqueda = new ControladorBusqueda();
      Object[][] datosTabla;
      String[] columnas = {"idcompra","Placa Base","Procesador","Ram","Tarjeta Video","Discos Duro","Fuente","Gabinete"};
public void mostrartabla(){
        datosTabla=cbusqueda.muestraUsuario();
        DefaultTableModel datos = new DefaultTableModel(datosTabla,columnas);
        TablaCar.setModel(datos);
    }
    public void busqueda(String parametro){
        datosTabla=cbusqueda.busqueda(parametro);
        DefaultTableModel datos = new DefaultTableModel(datosTabla,columnas);
        TablaCar.setModel(datos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCar = new javax.swing.JTable();
        jTFGabinete = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFPlacaBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFProcesador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFRam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFTarjetaV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFDd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFFuente = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaCar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 595, 93));
        getContentPane().add(jTFGabinete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, -1));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setText("Gabinete:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setText("Placa Base:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(jTFPlacaBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setText("Procesador:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        getContentPane().add(jTFProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 180, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel4.setText("Ram:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(jTFRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setText("Tarjeta de Vídeo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));
        getContentPane().add(jTFTarjetaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 180, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setText("Disco Duro:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(jTFDd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 180, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setText("Fuente:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        getContentPane().add(jTFFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 180, -1));

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, 60));

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modificar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
       
        String  [] registro = {jTFPlacaBase.getText(), jTFProcesador.getText(), 
            jTFRam.getText(), jTFTarjetaV.getText(), jTFDd.getText(), jTFFuente.getText(), 
            jTFGabinete.getText(), id};
        
    }//GEN-LAST:event_bActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCar;
    private javax.swing.JButton bActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDd;
    private javax.swing.JTextField jTFFuente;
    private javax.swing.JTextField jTFGabinete;
    private javax.swing.JTextField jTFPlacaBase;
    private javax.swing.JTextField jTFProcesador;
    private javax.swing.JTextField jTFRam;
    private javax.swing.JTextField jTFTarjetaV;
    // End of variables declaration//GEN-END:variables
}
